### ISSUE TITLE
Portable Nuget with MSBuild targets

### ISSUE THREAD

**Issue by andersnm** [k-john-gough/gplex#3]
Hi,

I'd like to see GPLEX and GPPG switch to the .NET Core tooling and new csproj format and distribute an official Nuget package with binaries and MSBuild targets.

Just spent most of the weekend playing around with this. Are you interested in a PR or two?

Benefits:

- Portable to Mac and Linux
- Simple to use, just need to add `<PackageReference>` in csproj, plus some wiring
- Build the GPLEX/GPPG repos without manual .bat file or boostrap steps

**Comment by k-john-gough** [comment]
Hi,

 

Thanks for the email. Yes, I am interested in your suggestion. How much of the changes have you tried?

 

Regards

K John Gough

**Comment by andersnm** [comment]
Hi, it works locally, but still have to clean up a bit. I was able to push my gplex fork this morning, but computer crashed before I could push gppg. I will try and find time after work to resume.

Here's the main gplex commit for an early review:
https://github.com/andersnm/gplex/commit/33c4cb4c61bbf8c820b0f116660c9195da5cf76d

This won't work as-is though. The project both produces and depends on the non-existent Nuget package "Gplex.Tool" (and "Gppg.Tool"), which includes the executable and targets to invoke via MSBuild. I intend to publish bootstrap versions of these to Nuget asap.

Main changes:

- Move all source files to Gplex directory
- Embed resources via csproj
- Ported WinForms codegen based resource class to handcoded
- Build .lex and .yy from csproj with prebuilt tools from Nuget
- Builds binaries targeting net20 and netcoreapp2.0 => .NET Framework 2.0 and newer, .NET Core 2.0 and newer

There are zero changes in the source code of GPLEX itself.

The csproj build rules for .lex and .y files look like this:
https://github.com/andersnm/gplex/commit/33c4cb4c61bbf8c820b0f116660c9195da5cf76d#diff-c60646dd8050a860615e754c68328a0aR31-R38

There's some issues with MSBuild yet to resolve: The tools are run once for each target framework in multi/cross-targeting solutions, and generated files aren't built during the first build after cloning
